import { Movie, MovieCategory, WeeklyRankingItem } from './types';

export const movieCategories: MovieCategory[] = [
  { id: 'all', name: 'All', value: 'all' },
  { id: 'drama', name: 'Drama', value: 'drama' },
  { id: 'comedy', name: 'Comedy', value: 'comedy' },
  { id: 'action', name: 'Action', value: 'action' },
  { id: 'scifi', name: 'Science fiction', value: 'scifi' },
  { id: 'animation', name: 'Animation', value: 'animation' },
  { id: 'romance', name: 'Romance', value: 'romance' },
  { id: 'thriller', name: 'Thriller', value: 'thriller' },
  { id: 'fantasy', name: 'Fantasy', value: 'fantasy' },
  { id: 'crime', name: 'Crime', value: 'crime' },
  { id: 'family', name: 'Family', value: 'family' },
  { id: 'war', name: 'War', value: 'war' },
  { id: 'history', name: 'History', value: 'history' },
  { id: 'western', name: 'Western', value: 'western' },
  { id: 'musical', name: 'Musical', value: 'musical' },
  { id: 'sport', name: 'Sports', value: 'sport' },
  { id: 'documentary', name: 'Documentary', value: 'documentary' },
  { id: 'short', name: 'Short film', value: 'short' },
  { id: 'adult', name: 'Adult', value: 'adult' },
  { id: 'gay', name: 'LGBTQ+', value: 'gay' },
];

export const mockMovies: Movie[] = [
  {
    id: '1',
    title: 'Beyond the Edge',
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300&h=400&fit=crop',
    rating: 6.9,
    ratingCount: 57882,
    genres: ['Thriller', 'Science fiction', 'Drama'],
    year: '2025',
    country: 'United States / United Kingdom / Canada',
    directors: ['Alex Morgan'],
    actors: ['Jordan Lee', 'Alex Morgan', 'Taylor Chen'],
    description: 'Release: 2025-05-14 / Wide release: 2025-05-16',
    rank: 1,
    isHot: true
  },
  {
    id: '2',
    title: 'The Last Horizon',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=300&h=400&fit=crop',
    rating: 7.1,
    ratingCount: 2639,
    genres: ['Science fiction', 'Thriller', 'Drama'],
    year: '2025',
    country: 'United States / Canada',
    directors: ['Alex Morgan'],
    actors: ['Alex Morgan', 'Alex Morgan'],
    description: 'Release: 2025-06-18 / Wide release: 2025-06-20',
    rank: 2
  },
  {
    id: '3',
    title: 'Midnight Signal',
    poster: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=300&h=400&fit=crop',
    rating: 7.7,
    ratingCount: 42291,
    genres: ['Drama', 'Crime'],
    year: '2025',
    country: 'United States / Canada',
    directors: ['Alex Morgan'],
    actors: ['Alex Morgan', 'Alex Morgan'],
    description: 'Release: 2025-04-16 / Wide release: 2025-04-18',
    rank: 3
  },
  {
    id: '4',
    title: 'F1: The Movie',
    poster: 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=300&h=400&fit=crop',
    rating: 8.2,
    ratingCount: 15234,
    genres: ['Action', 'Sport', 'Drama'],
    year: '2025',
    country: 'United States / Canada',
    directors: ['Alex Morgan'],
    actors: ['Alex Morgan', 'Alex Morgan'],
    description: 'Release: 2025-06-27',
    rank: 4,
    isHot: true
  },
  {
    id: '5',
    title: 'Neon Streets',
    poster: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=300&h=400&fit=crop',
    rating: 6.8,
    ratingCount: 8956,
    genres: ['Action', 'Crime'],
    year: '2025',
    country: 'United States',
    directors: ['Morgan Reed'],
    actors: ['Jordan Lee', 'Taylor Chen'],
    description: 'Release: 2025-07-15',
    rank: 5
  },
  {
    id: '6',
    title: 'Orbitfall',
    poster: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=300&h=400&fit=crop',
    rating: 7.3,
    ratingCount: 23891,
    genres: ['Science fiction', 'Action'],
    year: '2025',
    country: 'United States',
    directors: ['Alex Morgan'],
    actors: ['Alex Morgan', 'Jordan Lee'],
    description: 'Release: 2025-03-21',
    rank: 6
  },
  {
    id: '7',
    title: 'The Iron Battalion',
    poster: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=300&h=400&fit=crop',
    rating: 8.1,
    ratingCount: 67234,
    genres: ['History', 'War', 'Drama'],
    year: '2024',
    country: 'United States / Canada',
    directors: ['Alex Morgan'],
    actors: ['Alex Morgan', 'Alex Morgan'],
    description: 'Release: 2024-11-22',
    rank: 7
  },
  {
    id: '8',
    title: 'Pixel Detectives',
    poster: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=300&h=400&fit=crop',
    rating: 7.9,
    ratingCount: 45672,
    genres: ['Animation', 'Comedy', 'Crime'],
    year: '2025',
    country: 'Japan',
    directors: ['Jamie Park'],
    actors: ['Jordan Lee', 'Jamie Park'],
    description: 'Release: 2025-04-19',
    rank: 8
  }
];

export const weeklyRanking: WeeklyRankingItem[] = [
  { id: '1', title: 'F1: The Movie', change: 10 },
  { id: '2', title: 'Midnight Signal', change: 1 },
  { id: '3', title: 'Orbitfall', change: 0 },
  { id: '4', title: 'Neon Streets', change: -2 },
  { id: '5', title: 'The Iron Battalion', change: 6 },
  { id: '6', title: 'Pixel Detectives', change: -5 },
  { id: '7', title: 'Beyond the Edge', change: 4 },
  { id: '8', title: 'Beyond the Edge', change: -3 },
  { id: '9', title: 'The Last Horizon', change: 2 },
  { id: '10', title: 'Midnight Signal', change: -1 }
]; 